#ifndef BVH_TOKEN_H
#define BVH_TOKEN_H

namespace BVHViewer_DataObjects
{
    // NT - non-terminal
    // TKW - terminal keyword (or special sign)
    // T - terminal
    enum BvhToken
    {
        E_BVH_TOKEN_NT_BOTTOM,
        E_BVH_TOKEN_NT_FILE,
        E_BVH_TOKEN_NT_HIERARCHY,
        E_BVH_TOKEN_NT_ROOT_LIST,
        E_BVH_TOKEN_NT_ROOT,
        E_BVH_TOKEN_NT_ROOT_LIST_CONTINUE,
        E_BVH_TOKEN_NT_OFFSET,
        E_BVH_TOKEN_NT_CHANNELS,
        E_BVH_TOKEN_NT_KEYWORD_POSITION_LIST,
        E_BVH_TOKEN_NT_KEYWORD_POSITION,
        E_BVH_TOKEN_NT_JOINT_LIST,
        E_BVH_TOKEN_NT_JOINT_LIST_CONTINUE,
        E_BVH_TOKEN_NT_MOTION,
        E_BVH_TOKEN_NT_MOTION_FLOAT_LIST,
        E_BVH_TOKEN_TKW_HIERARCHY,
        E_BVH_TOKEN_TKW_ROOT,
        E_BVH_TOKEN_TKW_JOINT,
        E_BVH_TOKEN_TKW_OFFSET,
        E_BVH_TOKEN_TKW_CHANNELS,
        E_BVH_TOKEN_TKW_XPOSITION,
        E_BVH_TOKEN_TKW_YPOSITION,
        E_BVH_TOKEN_TKW_ZPOSITION,
        E_BVH_TOKEN_TKW_XROTATION,
        E_BVH_TOKEN_TKW_YROTATION,
        E_BVH_TOKEN_TKW_ZROTATION,
        E_BVH_TOKEN_TKW_END,
        E_BVH_TOKEN_TKW_SITE,
        E_BVH_TOKEN_TKW_MOTION,
        E_BVH_TOKEN_TKW_FRAMES,
        E_BVH_TOKEN_TKW_FRAME,
        E_BVH_TOKEN_TKW_TIME,
        E_BVH_TOKEN_TKW_OPEN_BRACKET,
        E_BVH_TOKEN_TKW_CLOSE_BRACKET,
        E_BVH_TOKEN_TKW_COLON,
        E_BVH_TOKEN_T_IDENTIFIER,
        E_BVH_TOKEN_T_INTEGER_CHANNELS,
        E_BVH_TOKEN_T_INTEGER_FRAMES,
        E_BVH_TOKEN_T_FLOAT_OFFSET,
        E_BVH_TOKEN_T_FLOAT_FRAMETIME,
        E_BVH_TOKEN_T_FLOAT_MOTIONDATA
    };
}

#endif